## Activation Functions

In [3]:
import numpy as np

# Activation Functions
def sigmoid(x):
    """Sigmoid activation function"""
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    """Derivative of sigmoid function"""
    sig = sigmoid(x)
    return sig * (1 - sig)

def relu(x):
    """ReLU (Rectified Linear Unit) activation function"""
    return np.maximum(0, x)

def relu_derivative(x):
    """Derivative of ReLU"""
    return np.where(x > 0, 1, 0)

def leaky_relu(x, alpha=0.01):
    """Leaky ReLU activation function"""
    return np.where(x > 0, x, alpha * x)

def leaky_relu_derivative(x, alpha=0.01):
    """Derivative of Leaky ReLU"""
    return np.where(x > 0, 1, alpha)

def tanh(x):
    """Tanh activation function"""
    return np.tanh(x)

def tanh_derivative(x):
    """Derivative of Tanh"""
    return 1 - np.tanh(x) ** 2

def softmax(x):
    """Softmax activation function"""
    exp_x = np.exp(x - np.max(x))  # For numerical stability
    return exp_x / np.sum(exp_x, axis=0)

# Example Usage
if __name__ == "__main__":
    # Input array
    x = np.array([1, -2, 3, -4, 0])

    # Sigmoid
    print("Sigmoid:")
    print(sigmoid(x))
    print("Sigmoid Derivative:")
    print(sigmoid_derivative(x))

    # ReLU
    print("\nReLU:")
    print(relu(x))
    print("ReLU Derivative:")
    print(relu_derivative(x))

    # Leaky ReLU
    print("\nLeaky ReLU:")
    print(leaky_relu(x))
    print("Leaky ReLU Derivative:")
    print(leaky_relu_derivative(x))

    # Tanh
    print("\nTanh:")
    print(tanh(x))
    print("Tanh Derivative:")
    print(tanh_derivative(x))

    # Softmax (for a single vector)
    print("\nSoftmax:")
    print(softmax(x))


Sigmoid:
[0.73105858 0.11920292 0.95257413 0.01798621 0.5       ]
Sigmoid Derivative:
[0.19661193 0.10499359 0.04517666 0.01766271 0.25      ]

ReLU:
[1 0 3 0 0]
ReLU Derivative:
[1 0 1 0 0]

Leaky ReLU:
[ 1.   -0.02  3.   -0.04  0.  ]
Leaky ReLU Derivative:
[1.   0.01 1.   0.01 0.01]

Tanh:
[ 0.76159416 -0.96402758  0.99505475 -0.9993293   0.        ]
Tanh Derivative:
[0.41997434 0.07065082 0.00986604 0.00134095 1.        ]

Softmax:
[1.13462810e-01 5.64898068e-03 8.38383068e-01 7.64506400e-04
 4.17406351e-02]
